### PR TITLE
Scientific Linux 7.9 support

### PR DESCRIPTION
**Pull request by opoplawski**
This is my naive attempt at adding support for Scientific Linux 7.9.  Any guidance would be appreciated.

### CODE REVIEW

**Comment by opoplawski** [comment]
I should note that my goal here is to be able to upgrade Scientific Linux 7.9 to AlmaLinux 8.  Not sure if this is needed for that.

**Comment by andrewlukoshko** [comment]
Yes these changes are required.
Have you tested them?

**Comment by opoplawski** [comment]
Starting to look at it.  preupgrade completes.  The only things that seem relevant here are:
```
Risk Factor: high
Title: Packages from unknown repositories may not be installed
Summary: 1 packages may not be installed or upgraded due to repositories unknown to leapp:
- kernel-uek (repoid: ol8-uek)
Remediation: [hint] Please file a bug in http://bugzilla.redhat.com/ for leapp-repository component of the Red Hat Enterprise Linux product.
Key: 9a2b05abf8f45fd7915e52542887bb334bb218ea
```
I don't seem to have kernel-uek or ol8-uek referred to in my system.

```
Risk Factor: high
Title: Packages not signed by Red Hat found on the system
Summary: The following packages have not been signed by Red Hat and may be removed during the upgrade process in case Red Hat-signed packages to be removed during the upgrade depend on them:
- conda
- elevate-release
- epel-release
....
```
This seems fairly normal though.

```
Risk Factor: low
Title: Some enabled RPM repositories are unknown to Leapp
Summary: The following repositories with Red Hat-signed packages are unknown to Leapp:
- sl-security
- sl-fastbugs
- sl-extras
- sl
And the following packages installed from those repositories may not be upgraded:
...
```

Is there something I should do to make these repos "known" to Leapp?

**Comment by opoplawski** [comment]
Also:
```
Error: Transaction test error:
  file /etc/os-release from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
  file /etc/redhat-release from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
  file /etc/rpm/macros.dist from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
  file /etc/system-release from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
  file /etc/system-release-cpe from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
  file /usr/lib/systemd/system-preset/90-default.preset from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
```

**Comment by prilr** [comment]
> ```
> Error: Transaction test error:
>   file /etc/os-release from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
>   file /etc/redhat-release from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
>   file /etc/rpm/macros.dist from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
>   file /etc/system-release from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
>   file /etc/system-release-cpe from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
>   file /usr/lib/systemd/system-preset/90-default.preset from install of almalinux-release-8.6-2.el8.x86_64 conflicts with file from package sl-release-7.9-1.sl7.x86_64
> ```

I believe this is a result of the above issue - Leapp attempts to install a known AlmaLinux "release" package over an unknown Scientific one - because it is not aware of the associated Scientific repository.

To make the repositories known to the upgrade process, you'll need to create a corresponding set of data files.
AlmaLinux stores them in [this](https://github.com/AlmaLinux/leapp-repository/tree/almalinux) repository. 

Take a look [here](https://github.com/AlmaLinux/leapp-data/tree/devel/files), in the subdirectories. These are used to build corresponding `leapp-data-*` RPM packages you have probably seen before.

The files `leapp_upgrade_repositories.repo.el8` and `repomap.json.el8` are of the primary interest here - to list the repos Leapp should use during the upgrade, and to map the repos present on the system to them.

The format should be relatively simple to understand. Ask if you have any questions about it.

**Comment by opoplawski** [comment]
Thanks for merging this.  Any chance this will make it into a released rpm anytime soon?  Or is there somewhere I can collect a test version?

**Pull request merged**
