### PR TITLE
Add AlmaLinux, EuroLinux, Oracle, Rocky keys and allow to migrate from them

### PR DESCRIPTION
**Pull request by andrewlukoshko**

### CODE REVIEW

**Comment by andrewlukoshko** [comment]
@prilr could you please review?

I'm mostly interested in the following:
1. Oracle packages don't have PACKAGER tag. What will happen?
2. CentOS Stream 8 doesn't have minor version and I've added just 8. What will happen?

**Comment by prilr** [comment]
@andrewlukoshko Question 1 I'll have to examine in more detail, but I can tell you right away that 2 will be a problem, because that list is expected to be in a form of N.N, and Leapp will raise a ValueError if it sees something not matching that pattern.

**Comment by prilr** [comment]
@andrewlukoshko The only place where a missing packager would affect something with Oracle is the `gpg-pubkey` package. For it, the signature check is replaced with the packager check.

**Comment by andrewlukoshko** [comment]
@prilr I've decided to use 8.5 as allowed CentOS version for now.
If everything else is fine then I'll merge

**Pull request merged**
